---
title: "Project_3"
author: "Aaron Zelmanov"
date: "3/29/2021"
output:
  html_document:
    code_folding: hide
---
## {.tabset}

### Introduction 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(class)
library(caret)
library(gmodels)
library(InformationValue)

airline_train <- read.csv("train.csv")
airline_test <- read.csv("test.csv")

airline_train$X <- NULL
airline_train$id <- NULL
airline_train$Gender <- as.factor(airline_train$Gender)
airline_train$Customer.Type <- as.factor(airline_train$Customer.Type)
airline_train$Type.of.Travel <- as.factor(airline_train$Type.of.Travel)
airline_train$Class <- as.factor(airline_train$Class)
airline_train$satisfaction <- as.factor(airline_train$satisfaction)
```

### Data Exploration 

### Regression 

```{r}
logit_model <- glm(satisfaction ~., data = airline_train, family = "binomial")
summary(logit_model)

prediction <- predict(logit_model, newdata = airline_test, type = "response")

#optimal <- optimalCutoff(airline_test$satisfaction, prediction)[1]

binary_predictions <- ifelse(prediction > 0.5, 1, 0)

#airline_test_labels <- airline_test[airline_test, "satisfaction"]

CrossTable(x = airline_test$satisfaction, y = binary_predictions, prop.chisq = FALSE)
```

### KNN

### ANN

### Decision Tree 

### SVM 

### Combined Model 

### Conclusion 
